<?php

namespace Zerbikat\BackendBundle\Repository;

/**
 * FitxafamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitxafamiliaRepository extends \Doctrine\ORM\EntityRepository
{
}
