version:  '3.7'
services:
    mariadb:
        image: mariadb:10.5.3
        container_name: zerbikat-mariadb
        volumes:
            - mariadb_zerbikat:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=dbpass
            - MYSQL_DATABASE=zerbikat
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpass

        ports:
            - "3306:3306"
        networks:
            - zerbikatnet

    app:
        container_name: zerbikat-php
        env_file: ./.env
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - WITH_XDEBUG=true
                - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        depends_on:
            - mariadb
        volumes:
            - '.:/usr/src/app'
        user: ${USER_ID}:${GROUP_ID}
        environment:
            - APP_ENV=dev
            - PHP_IDE_CONFIG=serverName=zerbikat.test
            - XDEBUG_CONFIG=remote_host=172.28.64.123
        networks:
            - zerbikatnet

    nginx:
        container_name: zerbikat-nginx
        image: nginx:1.15.3-alpine
        volumes:
            - '.:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - app
        ports:
            - "80:80"
        networks:
            - zerbikatnet

volumes:
    mariadb_zerbikat:

networks:
    zerbikatnet:
        driver: bridge
