easy_admin:
    design:
      menu:
        - { label: 'Taula Nagusiak' }
        - { label: 'Fitxak', entity: 'Fitxa', default: true }
        - Araudia
        - { label: 'Agiriak', entity: 'Dokumentazioa' }
        - { label: 'Sailak', entity: 'Saila' }
        - { label: 'Azpisailak', entity: 'Azpisaila' }
        - { label: 'Datuen Babesa', entity: 'Datuenbabesa' }
        - { label: 'Taula Laguntzaileak' }
        - label: 'Sailkapena'
#         icon: 'users'
          children:
            - { label: 'Etiketak', icon: 'file-new', entity: 'Etiketa' }
            - { label: 'Familiak', icon: 'file-list', entity: 'Familia' }
#           - { label: 'Payments Received', entity: 'Payment', params: { sortField: 'paidAt' } }
        - label: 'Taula Laguntzaileak'
          children:
            - { label: 'Epe arruntak', icon: 'file-new', entity: 'Arrunta' }
            - { label: 'Aurreikusitako epeak', icon: 'file-new', entity: 'Aurreikusi' }
            - { label: 'Arau-motak', icon: 'file-new', entity: 'Araumota' }
            - { label: 'Dokumentu-mota', icon: 'file-new', entity: 'Dokumentumota' }
            - { label: 'Ebazleak', icon: 'file-new', entity: 'Norkebatzi' }
            - { label: 'Tramiteak', icon: 'file-new', entity: 'Tramitea' }
            - { label: 'Kanal-motak', icon: 'file-new', entity: 'Kanalmota' }
            - { label: 'Kanalak', icon: 'file-new', entity: 'Kanala' }
            - { label: 'Taula gehigarria (besteak1)', icon: 'file-new', entity: 'Besteak1' }
            - { label: 'Taula gehigarria (besteak2)', icon: 'file-new', entity: 'Besteak2' }
            - { label: 'Taula gehigarria (besteak3)', icon: 'file-new', entity: 'Besteak3' }
        - label: 'KUDEAKETA'
          children:
            - { label: 'Zerbitzuak', icon: 'file-new', entity: 'Zerbitzua' }
            - { label: 'Udalak', icon: 'file-new', entity: 'Udala' }
            - { label: 'Eremuen konfigurazioa', icon: 'file-new', entity: 'Eremuak' }
            - { label: 'Espediente-kudeaketa', icon: 'file-new', entity: 'Espedientekudeaketa' }
            - { label: 'Erabiltzaileak', icon: 'file-new', entity: 'User' }

        - label: 'Zerga Ordenantzak'
          children:
            - { label: 'Ordenantzak', icon: 'file-new', entity: 'Ordenantza' }
            - { label: 'Atalak', icon: 'file-new', entity: 'Atala' }
            - { label: 'Taulak', icon: 'file-new', entity: 'Azpiatala' }
            - { label: 'Baldintzak', icon: 'file-new', entity: 'Baldintza' }
            - { label: 'Kontzeptu-motak', icon: 'file-new', entity: 'Kontzeptumota' }