easy_admin:
    design:
      menu:
        - { label: 'Taula Nagusiak' }
        - { label: 'Fitxak', entity: 'Fitxa', default: true }
        - Araudia
        - { label: 'Agiriak', entity: 'Dokumentazioa' }
        - { label: 'Sailak', entity: 'Saila' }
        - { label: 'Azpisailak', entity: 'Azpisaila' }
        - { label: 'Datuen Babesa', entity: 'Datuenbabesa' }


        - { label: 'BESTE TAULAK' }
        - label: 'BESTE TAULAK'
          children:
            - { label: 'Dokumentazio lagungarria', entity: 'Doklagun' }
            - { label: 'Prozedurak', entity: 'Prozedura' }
            - { label: 'Kanalak', entity: 'Kanala' }
            - { label: 'Taula gehigarria (besteak1)',  entity: 'Besteak1' }
            - { label: 'Taula gehigarria (besteak2)',  entity: 'Besteak2' }
            - { label: 'Taula gehigarria (besteak3)', entity: 'Besteak3' }
#        - { label: 'TAULA LAGUNGARRIAK' }
        - label: 'SAILKAPENA'
#         icon: 'users'
          children:
            - { label: 'Etiketak', icon: 'file-new', entity: 'Etiketa' }
            - { label: 'Familiak', icon: 'file-list', entity: 'Familia' }
#           - { label: 'Payments Received', entity: 'Payment', params: { sortField: 'paidAt' } }
        - label: 'Taula Lagungarriak'
          children:
            - { label: 'Epe arruntak', icon: 'file-new', entity: 'Arrunta' }
            - { label: 'Aurreikusitako epeak', icon: 'file-new', entity: 'Aurreikusi' }
            - { label: 'Isiltasun administratiboa', icon: 'file-new', entity: 'IsiltasunAdministratiboa' }
            - { label: 'Nork eska dezake', icon: 'file-new', entity: 'Norkeskatu' }
            - { label: 'Arau-motak', icon: 'file-new', entity: 'Araumota' }
            - { label: 'Dokumentu-mota', icon: 'file-new', entity: 'Dokumentumota' }
            - { label: 'Ebazleak', icon: 'file-new', entity: 'Norkebatzi' }
            - { label: 'Kanal-motak', icon: 'file-new', entity: 'Kanalmota' }

        - label: 'KUDEAKETA'
          children:
            - { label: 'Udalak', icon: 'file-new', entity: 'Udala' }
            - { label: 'Erabiltzaileak', icon: 'file-new', entity: 'User' }
            - { label: 'Eremuen konfigurazioa', icon: 'file-new', entity: 'Eremuak' }
            - { label: 'Espediente-kudeaketa', icon: 'file-new', entity: 'Espedientekudeaketa' }
            - { label: 'Zerbitzuak', icon: 'file-new', entity: 'Zerbitzua' }

        - label: 'KALE IZENDEGIA'
          children:
            - { label: 'Barrutiak', icon: 'file-new', entity: 'Barrutia' }
            - { label: 'Kaleak', icon: 'file-new', entity: 'Kalea' }
            - { label: 'Eraikinak', icon: 'file-new', entity: 'Eraikina' }

        - label: 'Zerga Ordenantzak'
          children:
            - { label: 'Ordenantzak', icon: 'file-new', entity: 'Ordenantza' }
            - { label: 'Atalak', icon: 'file-new', entity: 'Atala' }
            - { label: 'Taulak', icon: 'file-new', entity: 'Azpiatala' }
            - { label: 'Kontzeptuak', icon: 'file-new', entity: 'Kontzeptua' }
            - { label: 'Baldintzak', icon: 'file-new', entity: 'Baldintza' }
            - { label: 'Kontzeptu-motak', icon: 'file-new', entity: 'Kontzeptumota' }