imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BackendBundle/Resources/config/services.yml" }
    - { resource: admin/ }
    - { resource: "@FrontendBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: eu

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    formats:
      date:     'Y/m/d'
      time:     'H:i'
      datetime: 'Y/m/d H:i:s'
#    design:
#      brand_color: 'Red'
    entities:
      - Zerbikat\BackendBundle\Entity\Araudia
      - Zerbikat\BackendBundle\Entity\Araumota
      - Zerbikat\BackendBundle\Entity\Arrunta
      - Zerbikat\BackendBundle\Entity\Atala
      - Zerbikat\BackendBundle\Entity\Atalaparrafoa
      - Zerbikat\BackendBundle\Entity\Aurreikusi
      - Zerbikat\BackendBundle\Entity\Azpiatala
      - Zerbikat\BackendBundle\Entity\Azpiatalaparrafoa
      - Zerbikat\BackendBundle\Entity\Azpisaila
      - Zerbikat\BackendBundle\Entity\Baldintza
      - Zerbikat\BackendBundle\Entity\Barrutia
      - Zerbikat\BackendBundle\Entity\Datuenbabesa
      - Zerbikat\BackendBundle\Entity\Dokumentazioa
      - Zerbikat\BackendBundle\Entity\Dokumentumota
      - Zerbikat\BackendBundle\Entity\Eraikina
      - Zerbikat\BackendBundle\Entity\Etiketa
      - Zerbikat\BackendBundle\Entity\Familia
      - Zerbikat\BackendBundle\Entity\Fitxa
      - Zerbikat\BackendBundle\Entity\FitxaAraudia
      - Zerbikat\BackendBundle\Entity\FitxaDokumentazioa
      - Zerbikat\BackendBundle\Entity\FitxaTramitea
      - Zerbikat\BackendBundle\Entity\Kalea
      - Zerbikat\BackendBundle\Entity\Kontzeptua
      - Zerbikat\BackendBundle\Entity\Kontzeptumota
      - Zerbikat\BackendBundle\Entity\Norkebatzi
      - Zerbikat\BackendBundle\Entity\Ordenantza
      - Zerbikat\BackendBundle\Entity\Ordenantzaparrafoa
      - Zerbikat\BackendBundle\Entity\Saila
      - Zerbikat\BackendBundle\Entity\Tramitea
      - Zerbikat\BackendBundle\Entity\Kanalmota
      - Zerbikat\BackendBundle\Entity\Kanala
      - Zerbikat\BackendBundle\Entity\Zerbitzua
      - Zerbikat\BackendBundle\Entity\Udala
      - Zerbikat\BackendBundle\Entity\Espedientekudeaketa
      - Zerbikat\BackendBundle\Entity\Eremuak

ivory_ck_editor:
    input_sync: true
    default_config: simple_config
    configs:
        simple_config:
            toolbar:
                - { name: "styles", items: ['Source','Bold', 'Italic','Underline', 'BulletedList','NumberedList','Outdent','Indent', 'Link', 'PasteText'] }


nelmio_api_doc: ~




fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    routing_loader:
            default_format: json