easy_admin:
    entities:
        Araumota:
            class: Zerbikat\BackendBundle\Entity\Araumota
            label: 'Arau-motak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'kodea', label: 'Kodea' }
                    - { property: 'motaeu', label: 'Mota (eu)' }
                    - { property: 'motaes', label: 'Mota (es)' }
            form:
                fields:
                    - { property: 'kodea', label: 'Kodea', css_class: 'col-sm-2' }
                    - { property: 'motaeu', label: 'Mota (eu)', css_class: 'col-sm-5' }
                    - { property: 'motaes', label: 'Mota (eu)', css_class: 'col-sm-5' }
#                    - udala