easy_admin:
    entities:
        Arrunta:
            class: Zerbikat\BackendBundle\Entity\Arrunta
            label: 'Epe arruntak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'epeaeu', label: 'Epea (eu)' }
                    - { property: 'epeaes', label: 'Epea (es)' }
            form:
                fields:
                    - { property: 'epeaeu', label: 'Epea (eu)', css_class: 'col-sm-6' }
                    - { property: 'epeaes', label: 'Epea (eu)', css_class: 'col-sm-6' }
#                    - udala