easy_admin:
    entities:
        Azpisaila:
            class: Zerbikat\BackendBundle\Entity\Azpisaila
            label: 'Azpi-sail zerrenda'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'Kodea'
                    - { property: 'azpisailaeu', label: 'Azpi-Saila' }
                    - { property: 'arduraduna', label: 'Arduraduna' }
#                    - 'Araumota'
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'