easy_admin:
    entities:
        Azpisaila:
            class: Zerbikat\BackendBundle\Entity\Azpisaila
            label: 'Azpi-sail zerrenda'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'Kodea'
                    - { property: 'azpisailaeu', label: 'Azpi-Saila' }
                    - { property: 'arduraduna', label: 'Arduraduna' }
#                    - 'Araumota'
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'

            form:
                fields:
                    - { property: 'kodea', label: 'Kodea', css_class: 'col-sm-3' }
                    - { property: 'hizkia', label: 'Hizkia', css_class: 'col-sm-3' }
                    - { property: 'saila', label: 'Saila', css_class: 'col-sm-6' }
                    - { property: 'azpisailaeu', label: 'Azpi-saila (eu)', css_class: 'col-sm-6' }
                    - { property: 'azpisailaes', label: 'Azpi-saila (es)', css_class: 'col-sm-6' }
                    - { property: 'arduraduna', label: 'Arduraduna', css_class: 'col-sm-6' }
                    - { property: 'arduradunahaz', label: 'HAZ Arduraduna', css_class: 'col-sm-6' }
                    - { property: 'email', label: 'Email-a',type: 'url', css_class: 'col-sm-3' }
                    - { property: 'telefonoa', label: 'Telefonoa', css_class: 'col-sm-3' }
                    - { property: 'fax', label: 'FAX zenbakia', css_class: 'col-sm-3' }
                    - { property: 'ordutegia', label: 'Ordutegia', css_class: 'col-sm-3' }

                    - { property: 'barrutia', label: 'Barrutia', css_class: 'col-sm-3'}
                    - { property: 'kalea', label: 'Kalea' ,css_class: 'col-sm-4'}
                    - { property: 'kaleZbkia', label: 'Kale-zbkia', css_class: 'col-sm-1'}
                    - { property: 'eraikina', label: 'Eraikina' ,css_class: 'col-sm-4'}
#                    - udala



