easy_admin:
    entities:
        Azpiatala:
            class: Zerbikat\BackendBundle\Entity\Azpiatala
            label: 'Taulen zerrenda'
#            templates:
#                show: 'easy_admin/azpiatala.show.html.twig'

            list:
                max_results: 130
                title: '%%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'kodea', label: 'Taula Kodea' }
                    - { property: 'izenburuaeu', label: 'Izenburua' }
#                   - { property: 'azpisaila', label: 'Azpisaila' }

#            show:
#                fields:
#                    - { property: 'atala', label: 'Atala', css_class: 'col-sm-10' }
#                    - { property: 'kodea', label: 'Kodea', css_class: 'col-sm-2' }
#                    - { property: 'izenburuaeu', label: 'Izenburua (eu)', css_class: 'col-sm-6 large' }
#                    - { property: 'izenburuaes', label: 'Izenburua (es)', css_class: 'col-sm-6 large' }
#                    - Udala
#                    - Fitxak
#                    - Parrafoak
#                    - createdAt
#                    - updatedAt