easy_admin:
    entities:
        Baldintza:
            class: Zerbikat\BackendBundle\Entity\Baldintza
            label: 'Baldintzak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
#                    - { property: 'kodea', label: 'Atal Kodea' }
                    - { property: 'baldintzaeu', label: 'Baldintza' }
#                   - { property: 'azpisaila', label: 'Azpisaila' }

            form:
                fields:
                    - { property: 'baldintzaeu', label: 'Baldintza (eu)', css_class: 'col-sm-6' }
                    - { property: 'baldintzaes', label: 'Baldintza (es)', css_class: 'col-sm-6' }
#                    - Udala