easy_admin:
    entities:
        Besteak3:
            class: Zerbikat\BackendBundle\Entity\Besteak3
            label: 'Besteak3'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'Kodea'
                    - { property: 'izenburuaeu', label: 'Izenburua' }

            form:
                fields:
                    - { property: 'kodea', label: 'Kodea' }
                    - { property: 'izenburuaeu', label: 'Izenburua (eu)' }
                    - { property: 'izenburuaes', label: 'Izenburua (es)' }
                    - { property: 'estekaeu', label: 'Esteka (eu)', type: 'url' }
                    - { property: 'estekaes', label: 'Esteka (es)', type: 'url' }
#                    - udala