easy_admin:
    entities:
        Doklagun:
            class: Zerbikat\BackendBundle\Entity\Doklagun
            label: 'Dokumentazio lagungarriak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'Kodea'
                    - { property: 'deskribapenaeu', label: 'Agiria' }
            form:
                fields:
                    - { property: 'kodea', label: 'Kodea', css_class: 'col-sm-8' }
                    - { property: 'deskribapenaeu', label: 'Deskribapena (eu)',type: 'text', css_class: 'col-sm-6'}
                    - { property: 'deskribapenaes', label: 'Deskribapena (es)',type: 'text', css_class: 'col-sm-6' }
                    - { property: 'estekaeu', label: 'Esteka (eu)', css_class: 'col-sm-6' }
                    - { property: 'estekaes', label: 'Esteka (es)', css_class: 'col-sm-6' }
#                    - udala