easy_admin:
    entities:
        Dokumentazioa:
            class: Zerbikat\BackendBundle\Entity\Dokumentazioa
            label: 'Agiri zerrenda'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'Kodea'
#                    - { property: 'dokumentumota', label: 'Agiri-mota' }
                    - { property: 'deskribapenaeu', label: 'Agiria' }
#                    - 'Araumota'
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'