easy_admin:
    entities:
        Dokumentazioa:
            class: Zerbikat\BackendBundle\Entity\Dokumentazioa
            label: 'Agiri zerrenda'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'Kodea'
#                    - { property: 'dokumentumota', label: 'Agiri-mota' }
                    - { property: 'deskribapenaeu', label: 'Agiria' }
#                    - 'Araumota'
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'
            form:
                fields:
                    - { property: 'kodea', label: 'Kodea', css_class: 'col-sm-2' }
                    - { property: 'dokumentumota', label: 'Dokumentu-mota', css_class: 'col-sm-6' }
                    - { property: 'deskribapenaeu', label: 'Deskribapena (eu)', type: 'text' }
                    - { property: 'deskribapenaes', label: 'Deskribapena (es)', type: 'text' }
#                    - { property: 'deskribapenaeu', label: 'Deskribapena (eu)', type: 'ckeditor' }
#                    - { property: 'deskribapenaes', label: 'Deskribapena (es)', type: 'ckeditor' }
                    - { property: 'estekaeu', label: 'Esteka (eu)' }
                    - { property: 'estekaes', label: 'Esteka (es)' }

#                    - udala