easy_admin:
    entities:
        Eremuak:
            class: Zerbikat\BackendBundle\Entity\Eremuak
            label: 'Eremuak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: '-delete', label: '', icon: 'trash' }
                fields:
                    - Udala
                    - { property: 'oharraktext', label: 'Oharrak (Txt)' }
#                    - { property: 'helburuatext', label: 'Helburua (Txt)' }
#                    - { property: 'ebazpensinpli', label: 'Ebazpen-Sinplifikatua' }
#                    - { property: 'arduraaitorpena', label: 'Ardura aitorpena' }
#                    - { property: 'aurreikusi', label: 'Aurreikusitako epea' }
                    - { property: 'arrunta', label: 'Epe Arrunta' }
                    - { property: 'isiltasunadmin', label: 'Administrazio Isiltasuna' }
                    - { property: 'kanalatext', label: 'Kanala txt' }
                    - { property: 'kanalatable', label: 'Kanala table' }

            form:
                fields:
                    - { property: 'oharraktext', label: 'Oharrak', css_class: 'col-sm-4 large' }
                    - { property: 'oharraklabeleu', label: 'Oharrak etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'oharraklabeles', label: 'Oharrak etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'helburuatext', label: 'Helburua', css_class: 'col-sm-4 large' }
                    - { property: 'helburualabeleu', label: 'Helburua etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'helburualabeles', label: 'Helburua etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'ebazpensinpli', label: 'Ebazpen sinplifikatua', css_class: 'col-sm-4 large' }
                    - { property: 'ebazpensinplilabeleu', label: 'Ebazpen sinplifikatua etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'ebazpensinplilabeles', label: 'Ebazpen sinplifikatua etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'arduraaitorpena', label: 'Ardura aitorpena', css_class: 'col-sm-4 large' }
                    - { property: 'arduraaitorpenalabeleu', label: 'Ardura Aitorpena etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'arduraaitorpenalabeles', label: 'Ardura Aitorpena etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'aurreikusi', label: 'Aurreikusitako epea', css_class: 'col-sm-4 large' }
                    - { property: 'aurreikusilabeleu', label: 'Aurreikusitako epea etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'aurreikusilabeles', label: 'Aurreikusitako epea etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'arrunta', label: 'Epe Arrunta', css_class: 'col-sm-4 large' }
                    - { property: 'arruntalabeleu', label: 'Epe Arrunta etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'arruntalabeles', label: 'Epe Arrunta etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'isiltasunadmin', label: 'Administrazio isiltasunaren izaera', css_class: 'col-sm-4 large' }
                    - { property: 'isiltasunadminlabeleu', label: 'Administrazio isiltasuna etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'isiltasunadminlabeles', label: 'Administrazio isiltasuna etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'dokumentazioatext', label: 'Agiriak (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'dokumentazioatable', label: 'Agiriak (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'dokumentazioalabeleu', label: 'Agiriak etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'dokumentazioalabeles', label: 'Agiriak etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'kostuatext', label: 'Kostua (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'kostuatable', label: 'Kostua (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'kostualabeleu', label: 'Kostua etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'kostualabeles', label: 'Kostua etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'araudiatext', label: 'Araudia (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'araudiatable', label: 'Araudia (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'araudialabeleu', label: 'Araudia etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'araudialabeles', label: 'Araudia etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'prozeduratext', label: 'Prozedurak (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'prozeduratable', label: 'Prozedurak (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'prozeduralabeleu', label: 'Prozedurak etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'prozeduralabeles', label: 'Prozedurak etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'tramiteatext', label: 'Tramiteak (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'tramiteatable', label: 'Tramiteak (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'tramitealabeleu', label: 'Tramiteak etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'tramitealabeles', label: 'Tramiteak etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'norkebatzitext', label: 'Nork ebatzi (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'norkebatzitable', label: 'Nork ebatzi (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'norkebatzilabeleu', label: 'Nork ebatzi etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'norkebatzilabeles', label: 'Nork ebatzi etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'azpisailatable', label: 'Udal saila (taula)', css_class: 'col-sm-4 large' }
                    - { property: 'azpisailalabeleu', label: 'Udal saila (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'azpisailalabeles', label: 'Udal saila (es)', css_class: 'col-sm-4 large' }

                    - { property: 'doklaguntext', label: 'Dok. lag. (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'doklaguntable', label: 'Dok. lag. (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'doklagunlabeleu', label: 'Dok. lagun. etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'doklagunlabeles', label: 'Dok. lagun. etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'datuenbabesatext', label: 'D. Babesa (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'datuenbabesatable', label: 'D. Babesa (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'datuenbabesalabeleu', label: 'Datuen-babesa etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'datuenbabesalabeles', label: 'Datuen-babesa etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'norkeskatutext', label: 'Nork eskatu(txt)', css_class: 'col-sm-2 large' }
                    - { property: 'norkeskatutable', label: 'Nork eskatu(taula)', css_class: 'col-sm-2 large' }
                    - { property: 'norkeskatulabeleu', label: 'Nork eska dezake etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'norkeskatulabeles', label: 'Nork eska dezake etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'besteak1text', label: 'Besteak1 (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'besteak1table', label: 'Besteak1 (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'besteak1labeleu', label: 'Besteak1 etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'besteak1labeles', label: 'Besteak1 etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'besteak2text', label: 'Besteak2 (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'besteak2table', label: 'Besteak2 (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'besteak2labeleu', label: 'Besteak2 etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'besteak2labeles', label: 'Besteak2 etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'besteak3text', label: 'Besteak3 (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'besteak3table', label: 'Besteak3 (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'besteak3labeleu', label: 'Besteak3 etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'besteak3labeles', label: 'Besteak3 etiketa (es)', css_class: 'col-sm-4 large' }

                    - { property: 'kanalatext', label: 'Kanala (txt)', css_class: 'col-sm-2 large' }
                    - { property: 'kanalatable', label: 'Kanala (taula)', css_class: 'col-sm-2 large' }
                    - { property: 'kanalalabeleu', label: 'Kanala etiketa (eu)', css_class: 'col-sm-4 large' }
                    - { property: 'kanalalabeles', label: 'Kanala etiketa (es)', css_class: 'col-sm-4 large' }

#                    - { property: 'udalsailalabeleu', label: 'Udal saila etiketa (eu)', css_class: 'col-sm-5 large' }
#                    - { property: 'udalsailalabeles', label: 'Udal saila etiketa (es)', css_class: 'col-sm-5 large' }
                    - { property: 'epealabeleu', label: 'Prozeduraren epea etiketa (eu)', css_class: 'col-sm-5 large' }
                    - { property: 'epealabeles', label: 'Prozeduraren epea etiketa (es)', css_class: 'col-sm-5 large' }
                    - { property: 'doanlabeleu', label: 'Kostua hutsik dagoeneko etiketa (eu)', css_class: 'col-sm-5 large' }
                    - { property: 'doanlabeles', label: 'Kostua hutsik dagoeneko etiketa (es)', css_class: 'col-sm-5 large' }

                    - { property: 'udala', type_options: { placeholder: 'Aukeratu Udala...' } }
