easy_admin:
    entities:
        Etiketa:
            class: Zerbikat\BackendBundle\Entity\Etiketa
            label: 'Etiketak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'etiketaeu', label: 'Etiketa (eu)' }
                    - { property: 'etiketaes', label: 'Etiketa (es)' }

            form:
                fields:
                    - { property: 'etiketaeu', label: 'Etiketa (eu)', css_class: 'col-sm-10' }
                    - { property: 'etiketaes', label: 'Etiketa (es)', css_class: 'col-sm-10' }
#                    - udala