easy_admin:
    entities:
        Kanala:
            class: Zerbikat\BackendBundle\Entity\Kanala
            label: 'Kanalak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'izenaeu', label: 'Kanala' }
                    - { property: 'deskribapenaeu', label: 'Deskribapena' }
                    - { property: 'kanalmota', label: 'Mota' }

            form:
                fields:
                    - { property: 'izenaeu', label: 'Izena (eu)', css_class: 'col-sm-12 large' }
                    - { property: 'izenaes', label: 'Izena (es)', css_class: 'col-sm-12 large' }
                    - { property: 'deskribapenaeu', label: 'Deskribapena (eu)', css_class: 'col-sm-12 large' }
                    - { property: 'deskribapenaes', label: 'Deskribapena (es)', css_class: 'col-sm-12 large' }
                    - { property: 'estekaeu', label: 'Esteka (eu): URL, email,....', css_class: 'col-sm-8 large' }
                    - { property: 'estekaes', label: 'Esteka (es): URL, email,....', css_class: 'col-sm-8 large' }
                    - { property: 'telefonoa', label: 'Telefono zenbakia', css_class: 'col-sm-6 large' }
                    - { property: 'fax', label: 'FAX zenbakia', css_class: 'col-sm-6 large' }
                    - { property: 'kanalmota', type_options: { placeholder: 'Aukeratu kanal-mota...' } }
                    - { property: 'udala', type_options: { placeholder: 'Aukeratu Udala...' } }
                    - { property: 'barrutia', type_options: { placeholder: 'Aukeratu barrutia...' } }
                    - { property: 'eraikina', type_options: { placeholder: 'Aukeratu eraikina...' } }
                    - { property: 'kalea', type_options: { placeholder: 'Aukeratu kalea...' }, css_class: 'col-sm-9' }
                    - { property: 'kalezbkia', label: 'Kale zenbakia', css_class: 'col-sm-3' }
