easy_admin:
    entities:
        Kanala:
            class: Zerbikat\BackendBundle\Entity\Kanala
            label: 'Kanalak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'izenaeu', label: 'Kanala' }
                    - { property: 'deskribapenaeu', label: 'Deskribapena' }
                    - { property: 'kanalmota', label: 'Mota' }

            form:
                fields:
                    - { property: 'telematikoa', label: 'Telematikoa da?', css_class: 'col-sm-10 large' }
                    - { property: 'izenaeu', label: 'Izena (eu)', css_class: 'col-sm-6 large' }
                    - { property: 'izenaes', label: 'Izena (es)', css_class: 'col-sm-6 large' }
                    - { property: 'deskribapenaeu', label: 'Deskribapena (eu)', css_class: 'col-sm-6 large' }
                    - { property: 'deskribapenaes', label: 'Deskribapena (es)', css_class: 'col-sm-6 large' }
                    - { property: 'estekaeu', label: 'Esteka (eu): URL, email,....', css_class: 'col-sm-6 large' }
                    - { property: 'estekaes', label: 'Esteka (es): URL, email,....', css_class: 'col-sm-6 large' }

                    - { property: 'kanalmota', type_options: { placeholder: 'Aukeratu kanal-mota...' }, css_class: 'col-sm-4' }
                    - { property: 'telefonoa', label: 'Telefono zenbakia', css_class: 'col-sm-4' }
                    - { property: 'fax', label: 'FAX zenbakia', css_class: 'col-sm-4' }

                    - { property: 'barrutia',label: 'Barrutia', type_options: { placeholder: 'Aukeratu barrutia...' }, css_class: 'col-sm-3' }
                    - { property: 'kalea',label: 'Kalea', type_options: { placeholder: 'Aukeratu kalea...' }, css_class: 'col-sm-4' }
                    - { property: 'kalezbkia', label: 'Kale-zbkia', css_class: 'col-sm-1' }
                    - { property: 'eraikina',label: 'Eraikina', type_options: { placeholder: 'Aukeratu eraikina...' }, css_class: 'col-sm-4' }

#                    - { property: 'udala', type_options: { placeholder: 'Aukeratu Udala...' } }