easy_admin:
    entities:
        Ordenantza:
            class: Zerbikat\BackendBundle\Entity\Ordenantza
            label: 'Ordenantza zerrenda'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'kodea', label: 'Ordenantza Kodea' }
                    - { property: 'izenburuaeu', label: 'Izenburua' }
#                    - { property: 'createdAt', label: 'Azpisaila' }
            form:
                fields:
                    - { property: 'kodea', label: 'Kodea' }
                    - { property: 'izenburuaeu', label: 'Izenburua (eu)' }
                    - { property: 'izenburuaes', label: 'Izenburua (es)' }
#                    - udala
#                    - createdAt
#                    - updatedAt