easy_admin:
    entities:
        Prozedura:
            class: Zerbikat\BackendBundle\Entity\Prozedura
            label: 'Prozedura zerrenda'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                   - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'prozeduraeu', label: 'Prozedura (eu)' }
                    - { property: 'prozeduraes', label: 'Prozedura (es)' }
            form:
                fields:
                    - { property: 'prozeduraeu', label: 'Prozedura (eu)', css_class: 'col-sm-6' }
                    - { property: 'prozeduraes', label: 'Prozedura (es)', css_class: 'col-sm-6' }
#                    - udala