easy_admin:
    entities:
        Udala:
            class: Zerbikat\BackendBundle\Entity\Udala
            label: 'Udalak'
            list:
                max_results: 50
                title: '%%entity_label%%'
                actions:
#                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'kodea', label: 'Udalaren Kodea' }
                    - { property: 'izenaeu', label: 'Udala' }
            form:
                fields:
                    - { property: 'kodea', label: 'Kodea', css_class: 'col-sm-2' }
                    - { property: 'ifk', label: 'IFK', css_class: 'col-sm-4' }
                    - { property: 'espedientekudeaketa',label: 'Espediente kudeaketa', type_options: { placeholder: 'Aukeratu espediente kudeaketa sistema...' }, css_class: 'col-sm-4' }
                    - { property: 'izenaeu', label: 'Izena (eu)', css_class: 'col-sm-6' }
                    - { property: 'izenaes', label: 'Izena (es)', css_class: 'col-sm-6' }
                    - { property: 'izendapenaeu', label: 'Izendapena (eu)', css_class: 'col-sm-6' }
                    - { property: 'izendapenaes', label: 'Izendapena (es)', css_class: 'col-sm-6' }
                    - { property: 'logoa', label: 'Logoa (url)' }
                    - { property: 'lopdeu', label: 'LOPD txantilla (eu)', type: 'ckeditor', css_class: 'col-sm-6' }
                    - { property: 'lopdes', label: 'LOPD txantilla (es)', type: 'ckeditor', css_class: 'col-sm-6' }
