easy_admin:
    entities:
        User:
            class: Zerbikat\BackendBundle\Entity\User
            label: 'Erabiltzaileak'

            list:
                title: '%%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: '-delete', label: '', icon: 'trash' }
                fields:
                    - id
                    - { property: 'username', label: 'Erabiltzailea' }
                    - email
            form:
                title: '%%entity_label%%'
                fields:
#                    - enabled
                    - { property: 'enabled', label: 'Aktibo?', css_class: 'col-sm-2' }
                    - { property: 'username', label: 'NA', css_class: 'col-sm-2' }
                    - { property: 'email', label: 'Email-a', css_class: 'col-sm-4' }
                    - { property: 'plainpassword', label: 'Pasahitza', css_class: 'col-sm-4', type: 'text' }
#                    - plainPassword
                    - { property: 'udala',label: 'Udala', type_options: { placeholder: 'Aukeratu udala...' }, css_class: 'col-sm-5' }
                    - { property: 'azpisaila',label: 'Saila', type_options: { placeholder: 'Aukeratu saila...' }, css_class: 'col-sm-5' }
                    - { property: 'roles',label: 'Rol-ak', css_class: 'col-sm-4' }
